# Generated by Django 4.2.7 on 2026-02-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='experience_years',
            field=models.CharField(default='0-1 Years', max_length=20),
        ),
    ]
