# Generated by Django 4.2.7 on 2026-02-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
